[package]
name = "simple_seq_cli"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "simple_seq_cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }